"""features table

Revision ID: d672f2011872
Revises: 
Create Date: 2019-07-21 15:51:47.864168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd672f2011872'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=True),
    sa.Column('value', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_features_key'), 'features', ['key'], unique=False)
    op.create_index(op.f('ix_features_value'), 'features', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_features_value'), table_name='features')
    op.drop_index(op.f('ix_features_key'), table_name='features')
    op.drop_table('features')
    # ### end Alembic commands ###
